const ecP256PrivateKeyPem = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgWICWJWyd0DAQIOeP
Y9AJir6aaGKmZLua9GZJU/LCQ9yhRANCAARV9trRKPxmsL5DHTEmRbasczLXy05k
RKwnE8ROAxaScnb80D3+rhmBsvf0Y6bN6tJwwuIuvPL7akuvKCnNfPy8
-----END PRIVATE KEY-----`

const ecP256Cert = `-----BEGIN CERTIFICATE-----
MIIDATCCAqegAwIBAgIUOtKsAoTe1XLW6LTc7l5UTFig2pgwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAX
DTI2MTAwNzE3MDMyOFoYDzk2OTIxMTI2MTcwMzI4WjBhMQswCQYDVQQGEwJVUzEN
MAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMRAw
DgYDVQQLDAdTaWduaW5nMREwDwYDVQQDDAhKb2huIERvZTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABFX22tEo/GawvkMdMSZFtqxzMtfLTmRErCcTxE4DFpJydvzQ
Pf6uGYGy9/Rjps3q0nDC4i688vtqS68oKc18/LyjggE+MIIBOjAJBgNVHRMEAjAA
MAsGA1UdDwQEAwIGwDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwMwLQYD
VR0fBCYwJDAioCCgHoYcaHR0cDovL2xvY2FsaG9zdDo4MDgwL2NhLmNybDCBkQYI
KwYBBQUHAQEEgYQwgYEwKAYIKwYBBQUHMAKGHGh0dHA6Ly9sb2NhbGhvc3Q6ODA4
MC9jYS5jcnQwJgYIKwYBBQUHMAGGGmh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9vY3Nw
MC0GCCsGAQUFBzABhiFodHRwOi8vbG9jYWxob3N0OjgwODAvb2NzcC1iYWNrdXAw
HQYDVR0OBBYEFHWJWE+MMoJVeSqEU/VVX8Ktz5uKMB8GA1UdIwQYMBaAFLhA0Ht0
LkMVNLJK1pK0cXLl6b7pMAoGCCqGSM49BAMCA0gAMEUCIQCbJGvB0GoC+ameBY69
g23iA5Swq7r4eBekFCELc9E/DAIgfs6LbtoSm/BGsWuQeGqXGJRn4DGVxKHOPJnH
5rRsJ7Y=
-----END CERTIFICATE-----`

const ecP256CaCert = `-----BEGIN CERTIFICATE-----
MIICDzCCAbWgAwIBAgIUBi3pgCwB1I6sGkuMB66ADfImIv8wCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAX
DTI2MTAwNzE3MDMyOFoYDzk5NjYwOTEyMTcwMzI4WjBcMQswCQYDVQQGEwJVUzEN
MAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQsw
CQYDVQQLDAJDQTERMA8GA1UEAwwITXlSb290Q0EwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAAR6qMU2BiX9GKLo2c+MGnKXE/UVNJlkpx5f+iGeUuRorAT9d3wlqDOX
sFfkDYipIw0XrReh3eXOfGZK3nWfV3KDo1MwUTAdBgNVHQ4EFgQUuEDQe3QuQxU0
skrWkrRxcuXpvukwHwYDVR0jBBgwFoAUuEDQe3QuQxU0skrWkrRxcuXpvukwDwYD
VR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiEAvmIpILeBpHTtitphp6rm
laiQ2alMgOAztzMn0RPWblgCIDRofM8IklLXPxOwFsl1p+oHmPVRnVE2Qk2ABjTN
3/Yd
-----END CERTIFICATE-----`

const ecP256CaCrl = `-----BEGIN X509 CRL-----
MIHzMIGbAgEBMAoGCCqGSM49BAMCMFwxCzAJBgNVBAYTAlVTMQ0wCwYDVQQIDARU
ZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UECgwFTXlPcmcxCzAJBgNVBAsMAkNB
MREwDwYDVQQDDAhNeVJvb3RDQRcNMjYxMDA3MTcwMzI4WhcNNDgwOTAxMTcwMzI4
WqAOMAwwCgYDVR0UBAMCAQEwCgYIKoZIzj0EAwIDRwAwRAIgRi1BZs/M2jwKhE18
Tn3Ugr0JLQl0RiVnsfoGgPiyTnUCIANQRBv7Fghoao1sWxbfyi5Aw4Fda/29MIqJ
gVwAK1un
-----END X509 CRL-----`

const ecP256OcspResponse = `-----BEGIN OCSP RESPONSE-----
MIIDuwoBAKCCA7QwggOwBgkrBgEFBQcwAQEEggOhMIIDnTCCAQShZjBkMQswCQYD
VQQGEwJVUzENMAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoM
BU15T3JnMQ0wCwYDVQQLDARPQ1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlchgP
MjAyNjEwMDcxNzAzMjhaMGQwYjBNMAkGBSsOAwIaBQAEFMMBXUhH1UJjC9/mkAgx
tU0Ghr32BBS4QNB7dC5DFTSyStaStHFy5em+6QIUOtKsAoTe1XLW6LTc7l5UTFig
2piCABgPMjAyNjEwMDcxNzAzMjhaoSMwITAfBgkrBgEFBQcwAQIEEgQQWBblGo6a
dW6lkLd0gOcgNTAKBggqhkjOPQQDAgNHADBEAiBqsqpQ2XfTwldsgFr2inPKZHE0
s4/favNoeM78FarQIQIgP1YNX8wBmnPXcguQJmxA25CiYB6JYtFIoPw2Smc+Z1ug
ggI8MIICODCCAjQwggHZoAMCAQICFDrSrAKE3tVy1ui03O5eVExYoNqZMAoGCCqG
SM49BAMCMFwxCzAJBgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYDVQQHDAVM
b2NhbDEOMAwGA1UECgwFTXlPcmcxCzAJBgNVBAsMAkNBMREwDwYDVQQDDAhNeVJv
b3RDQTAgFw0yNjEwMDcxNzAzMjhaGA85NjkyMTEyNjE3MDMyOFowZDELMAkGA1UE
BhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVN
eU9yZzENMAsGA1UECwwET0NTUDEXMBUGA1UEAwwOT0NTUCBSZXNwb25kZXIwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAARk6HbBuJ7w6YeRC0O3ydzYC3Pkv5KlasM6
lYtZ93Bf313Va99vY27EFGN57poWxe+Zbi2StLKeQGjQ9lvLnDPTo28wbTAJBgNV
HRMEAjAAMAsGA1UdDwQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDCTAdBgNVHQ4E
FgQUBLfgrMTbW0Hqv2Wn1/Ix1cNpLw8wHwYDVR0jBBgwFoAUuEDQe3QuQxU0skrW
krRxcuXpvukwCgYIKoZIzj0EAwIDSQAwRgIhAPW8mAKFuFT+h9D1BpwB+B9W7rs9
ffjFmqsJlQdtmptrAiEAzu5rWBnCfaE4SHPdjuKkvLdxgGCDzG0SD28ME6bA+TQ=
-----END OCSP RESPONSE-----`

function pemToUint8Array(
    pem: string | Uint8Array<ArrayBuffer>,
): Uint8Array<ArrayBuffer> {
    pem = typeof pem === 'string' ? pem : new TextDecoder().decode(pem)

    // Remove all headers, footers, and whitespace
    const b64 = pem
        .trim()
        .replace(/-----BEGIN [^-]+-----/, '')
        .replace(/-----END [^-]+-----/, '')
        .replace(/\s+/g, '')

    const binary = atob(b64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i)
    }

    return bytes
}

export const ecP256SigningKeys = {
    privateKey: pemToUint8Array(ecP256PrivateKeyPem),
    cert: pemToUint8Array(ecP256Cert),
    caCert: pemToUint8Array(ecP256CaCert),
    caCrl: pemToUint8Array(ecP256CaCrl),
    ocspResponse: pemToUint8Array(ecP256OcspResponse),
    privateKeyPem: ecP256PrivateKeyPem,
    certPem: ecP256Cert,
    caCertPem: ecP256CaCert,
    caCrlPem: ecP256CaCrl,
    ocspResponsePem: ecP256OcspResponse,
}
