const ed25519PrivateKeyPem = `-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIDBvJF3G75sLk3/L8FDm6amuOHVhhVuddcZcK3zIfP3u
-----END PRIVATE KEY-----`

const ed25519Cert = `-----BEGIN CERTIFICATE-----
MIICvzCCAnGgAwIBAgIUB5VfcPXvW98HTxsJqD23j/QYTqgwBQYDK2VwMFwxCzAJ
BgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UE
CgwFTXlPcmcxCzAJBgNVBAsMAkNBMREwDwYDVQQDDAhNeVJvb3RDQTAeFw0yNTA5
MjExMDU5MThaFw0yNjA5MjExMDU5MThaMGExCzAJBgNVBAYTAlVTMQ0wCwYDVQQI
DARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UECgwFTXlPcmcxEDAOBgNVBAsM
B1NpZ25pbmcxETAPBgNVBAMMCEpvaG4gRG9lMCowBQYDK2VwAyEAm1ZJ41jnQuLH
9TObZ5heMQjNFu2dph+5997WBZLD5sqjggE+MIIBOjAJBgNVHRMEAjAAMAsGA1Ud
DwQEAwIGwDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwMwLQYDVR0fBCYw
JDAioCCgHoYcaHR0cDovL2xvY2FsaG9zdDo4MDgwL2NhLmNybDCBkQYIKwYBBQUH
AQEEgYQwgYEwKAYIKwYBBQUHMAKGHGh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9jYS5j
cnQwJgYIKwYBBQUHMAGGGmh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9vY3NwMC0GCCsG
AQUFBzABhiFodHRwOi8vbG9jYWxob3N0OjgwODAvb2NzcC1iYWNrdXAwHQYDVR0O
BBYEFIFtAqEPSoknjwL2KboZ1O/wRDKoMB8GA1UdIwQYMBaAFKjnpYNruZq8Olnd
yY5uNtGHhbVTMAUGAytlcANBAD9NkZG/pCdLupv0PfheCZL2z16y+0vqyf/OSbpM
KmQTG7avNBvH1+qNo/XqGGqPnBgxUWzPCPAKy5MzgsFQXAg=
-----END CERTIFICATE-----`

const ed25519CaCert = `-----BEGIN CERTIFICATE-----
MIIBzTCCAX+gAwIBAgIUfmXBVL6Q3HuQd0WKpsXVLPJI4k0wBQYDK2VwMFwxCzAJ
BgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UE
CgwFTXlPcmcxCzAJBgNVBAsMAkNBMREwDwYDVQQDDAhNeVJvb3RDQTAeFw0yNTA5
MjExMDU5MThaFw0zNTA5MTkxMDU5MThaMFwxCzAJBgNVBAYTAlVTMQ0wCwYDVQQI
DARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UECgwFTXlPcmcxCzAJBgNVBAsM
AkNBMREwDwYDVQQDDAhNeVJvb3RDQTAqMAUGAytlcAMhAPQSFtTx7InMrk/9szSO
qRZEgVLc92VY0ys+nEF5pMVro1MwUTAdBgNVHQ4EFgQUqOelg2u5mrw6Wd3Jjm42
0YeFtVMwHwYDVR0jBBgwFoAUqOelg2u5mrw6Wd3Jjm420YeFtVMwDwYDVR0TAQH/
BAUwAwEB/zAFBgMrZXADQQCtz0LUv1WP7lttxAUHe7BwZ1MMG9qIvIWIXw5ZOePD
ceEI7hc7qU4ctY6AHBbKuspmbSvKCB+Y95geZzsJ6AsE
-----END CERTIFICATE-----`

const ed25519CaCrl = `-----BEGIN X509 CRL-----
MIHjMIGWAgEBMAUGAytlcDBcMQswCQYDVQQGEwJVUzENMAsGA1UECAwEVGVzdDEO
MAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYDVQQLDAJDQTERMA8G
A1UEAwwITXlSb290Q0EXDTI1MDkyMTEwNTkxOFoXDTI1MTAyMTEwNTkxOFqgDjAM
MAoGA1UdFAQDAgEBMAUGAytlcANBALvYSF73CaolL/9XPjoZ4qOlmk9OtJIZUhM+
5eE65cRhtCrwmPggmcDtoB3E+WhADREqB/1qfHD5l8gGihgMCAI=
-----END X509 CRL-----`

const ed25519OcspResponse = `-----BEGIN OCSP RESPONSE-----
MIIDbwoBAKCCA2gwggNkBgkrBgEFBQcwAQEEggNVMIIDUTCCAQShZjBkMQswCQYD
VQQGEwJVUzENMAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoM
BU15T3JnMQ0wCwYDVQQLDARPQ1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlchgP
MjAyNTA5MjExMDU5MThaMGQwYjBNMAkGBSsOAwIaBQAEFMMBXUhH1UJjC9/mkAgx
tU0Ghr32BBSo56WDa7mavDpZ3cmObjbRh4W1UwIUB5VfcPXvW98HTxsJqD23j/QY
TqiCABgPMjAyNTA5MjExMDU5MThaoSMwITAfBgkrBgEFBQcwAQIEEgQQnAs+s0p7
DNH24u+hGLLTvzAFBgMrZXADQQC/4tFcuMabq2upVpveLX9ZWBKDaCIUJdTDm9pE
3TzUiT+2YDtKohhvMD0qZDcYiDym2rdvUeg8n4lpAcEG5KUOoIIB+zCCAfcwggHz
MIIBpaADAgECAhQHlV9w9e9b3wdPGwmoPbeP9BhOqTAFBgMrZXAwXDELMAkGA1UE
BhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVN
eU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAXDTI1MDkyMTEw
NTkxOFoYDzIwNTMwMjA2MTA1OTE4WjBkMQswCQYDVQQGEwJVUzENMAsGA1UECAwE
VGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQ0wCwYDVQQLDARP
Q1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlcjAqMAUGAytlcAMhAKz1S3BLiyeK
sRKUImWYiLeK/0GuzvSVF1RkgW8KwZZuo28wbTAJBgNVHRMEAjAAMAsGA1UdDwQE
AwIHgDATBgNVHSUEDDAKBggrBgEFBQcDCTAdBgNVHQ4EFgQU+mZ+DKYXfYA/2xJk
Md81QrMdb8owHwYDVR0jBBgwFoAUqOelg2u5mrw6Wd3Jjm420YeFtVMwBQYDK2Vw
A0EA20R4OsVzKMhpIO1fRNagrm83QKiTL4W3YOGbyU8t/tLcDVsrhPSP6HY+LeqW
xm2gDYSqwnMscdm9yuFk9Wc7Bw==
-----END OCSP RESPONSE-----`

function pemToUint8Array(pem: string | Uint8Array): Uint8Array {
    pem = typeof pem === 'string' ? pem : new TextDecoder().decode(pem)

    // Remove all headers, footers, and whitespace
    const b64 = pem
        .trim()
        .replace(/-----BEGIN [^-]+-----/, '')
        .replace(/-----END [^-]+-----/, '')
        .replace(/\s+/g, '')

    const binary = atob(b64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i)
    }

    return bytes
}

export const ed25519SigningKeys = {
    privateKey: pemToUint8Array(ed25519PrivateKeyPem),
    cert: pemToUint8Array(ed25519Cert),
    caCert: pemToUint8Array(ed25519CaCert),
    caCrl: pemToUint8Array(ed25519CaCrl),
    ocspResponse: pemToUint8Array(ed25519OcspResponse),
    privateKeyPem: ed25519PrivateKeyPem,
    certPem: ed25519Cert,
    caCertPem: ed25519CaCert,
    caCrlPem: ed25519CaCrl,
    ocspResponsePem: ed25519OcspResponse,
}
