const ed25519PrivateKeyPem = `-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEICSjJXQKd4cXYXx16v3tUaOcQqNgYwDja/cJFHlLqkJB
-----END PRIVATE KEY-----`

const ed25519Cert = `-----BEGIN CERTIFICATE-----
MIICwTCCAnOgAwIBAgIUCfAyJahtY/9SBgB2Br9rsji+jKowBQYDK2VwMFwxCzAJ
BgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UE
CgwFTXlPcmcxCzAJBgNVBAsMAkNBMREwDwYDVQQDDAhNeVJvb3RDQTAgFw0yNjEw
MDcxNzAzMjlaGA85NjkyMTEyNjE3MDMyOVowYTELMAkGA1UEBhMCVVMxDTALBgNV
BAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzEQMA4GA1UE
CwwHU2lnbmluZzERMA8GA1UEAwwISm9obiBEb2UwKjAFBgMrZXADIQA/+LDxjihr
RVm3l4TfFvNdH3arGrQ29Z6Pk3UHDp0cMqOCAT4wggE6MAkGA1UdEwQCMAAwCwYD
VR0PBAQDAgbAMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAzAtBgNVHR8E
JjAkMCKgIKAehhxodHRwOi8vbG9jYWxob3N0OjgwODAvY2EuY3JsMIGRBggrBgEF
BQcBAQSBhDCBgTAoBggrBgEFBQcwAoYcaHR0cDovL2xvY2FsaG9zdDo4MDgwL2Nh
LmNydDAmBggrBgEFBQcwAYYaaHR0cDovL2xvY2FsaG9zdDo4MDgwL29jc3AwLQYI
KwYBBQUHMAGGIWh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9vY3NwLWJhY2t1cDAdBgNV
HQ4EFgQUZhiB64qZTFo17dLY+/yx84+ddzswHwYDVR0jBBgwFoAU4spDOueyMb/f
xedorYihCYDaxr4wBQYDK2VwA0EA3nnJUAZDUToJZ5bKboEPCw1+R2MT3TqZGV2c
93f0hXyYL9al+PJOeQ4oJTWMp1N/k4IEABdYTB+gpxhFHhzhAw==
-----END CERTIFICATE-----`

const ed25519CaCert = `-----BEGIN CERTIFICATE-----
MIIBzzCCAYGgAwIBAgIUKPe+/EWFWdEYYJjN4tFHr8PWCtcwBQYDK2VwMFwxCzAJ
BgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UE
CgwFTXlPcmcxCzAJBgNVBAsMAkNBMREwDwYDVQQDDAhNeVJvb3RDQTAgFw0yNjEw
MDcxNzAzMjlaGA85OTY2MDkxMjE3MDMyOVowXDELMAkGA1UEBhMCVVMxDTALBgNV
BAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzELMAkGA1UE
CwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCowBQYDK2VwAyEAAJkve9ZvZPVWO/nQ
ZIQFSYV7lyf6pLcpFB4cC/TcsY6jUzBRMB0GA1UdDgQWBBTiykM657Ixv9/F52it
iKEJgNrGvjAfBgNVHSMEGDAWgBTiykM657Ixv9/F52itiKEJgNrGvjAPBgNVHRMB
Af8EBTADAQH/MAUGAytlcANBADD5TurCR85Lh1/NflOkWw5jREHFxwyNTUv1Ruc9
4jmhomrmh25BRSGteYWoTC05PGfiuYTa4e41PabaD86rhgE=
-----END CERTIFICATE-----`

const ed25519CaCrl = `-----BEGIN X509 CRL-----
MIHjMIGWAgEBMAUGAytlcDBcMQswCQYDVQQGEwJVUzENMAsGA1UECAwEVGVzdDEO
MAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYDVQQLDAJDQTERMA8G
A1UEAwwITXlSb290Q0EXDTI2MTAwNzE3MDMyOVoXDTQ4MDkwMTE3MDMyOVqgDjAM
MAoGA1UdFAQDAgEBMAUGAytlcANBABujrlqVAXT6CVcERjIV1971hdyX+/yyVpj3
81WJ53MZRq5RJw0km1olqrxUEu6De9y06lr/EJuR9Q4Q3QdVAwk=
-----END X509 CRL-----`

const ed25519OcspResponse = `-----BEGIN OCSP RESPONSE-----
MIIDbwoBAKCCA2gwggNkBgkrBgEFBQcwAQEEggNVMIIDUTCCAQShZjBkMQswCQYD
VQQGEwJVUzENMAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoM
BU15T3JnMQ0wCwYDVQQLDARPQ1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlchgP
MjAyNjEwMDcxNzAzMjlaMGQwYjBNMAkGBSsOAwIaBQAEFMMBXUhH1UJjC9/mkAgx
tU0Ghr32BBTiykM657Ixv9/F52itiKEJgNrGvgIUCfAyJahtY/9SBgB2Br9rsji+
jKqCABgPMjAyNjEwMDcxNzAzMjlaoSMwITAfBgkrBgEFBQcwAQIEEgQQeGYcEzaI
tSNIQlUxBkk8xDAFBgMrZXADQQDbsez9cT7/lUGyl2v6yW1ylCg7qNaFooHqPGrM
oOnowLeWnUpM4uJnlBaBrPB5YbgP0pLgJAZJbqUSBpcJPYMAoIIB+zCCAfcwggHz
MIIBpaADAgECAhQJ8DIlqG1j/1IGAHYGv2uyOL6MqzAFBgMrZXAwXDELMAkGA1UE
BhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVN
eU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAXDTI2MTAwNzE3
MDMyOVoYDzk2OTIxMTI2MTcwMzI5WjBkMQswCQYDVQQGEwJVUzENMAsGA1UECAwE
VGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQ0wCwYDVQQLDARP
Q1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlcjAqMAUGAytlcAMhAEYRAjIS+z7y
Vb6ZOXE+9km0HE6U8pyA7zIqdnEaiBCLo28wbTAJBgNVHRMEAjAAMAsGA1UdDwQE
AwIHgDATBgNVHSUEDDAKBggrBgEFBQcDCTAdBgNVHQ4EFgQUXVzilyaKVoaPLOef
o3BQbK6bDMkwHwYDVR0jBBgwFoAU4spDOueyMb/fxedorYihCYDaxr4wBQYDK2Vw
A0EAyQFQrpMIlH+ixZsXckDwHZzIM2HHJHHHxqdvbQZSn8j8nCpr9FmLCmez6EXc
mT/t0+87FnOavznlHH3G7cC7Ag==
-----END OCSP RESPONSE-----`

function pemToUint8Array(
    pem: string | Uint8Array<ArrayBuffer>,
): Uint8Array<ArrayBuffer> {
    pem = typeof pem === 'string' ? pem : new TextDecoder().decode(pem)

    // Remove all headers, footers, and whitespace
    const b64 = pem
        .trim()
        .replace(/-----BEGIN [^-]+-----/, '')
        .replace(/-----END [^-]+-----/, '')
        .replace(/\s+/g, '')

    const binary = atob(b64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i)
    }

    return bytes
}

export const ed25519SigningKeys = {
    privateKey: pemToUint8Array(ed25519PrivateKeyPem),
    cert: pemToUint8Array(ed25519Cert),
    caCert: pemToUint8Array(ed25519CaCert),
    caCrl: pemToUint8Array(ed25519CaCrl),
    ocspResponse: pemToUint8Array(ed25519OcspResponse),
    privateKeyPem: ed25519PrivateKeyPem,
    certPem: ed25519Cert,
    caCertPem: ed25519CaCert,
    caCrlPem: ed25519CaCrl,
    ocspResponsePem: ed25519OcspResponse,
}
