const ecP384PrivateKeyPem = `-----BEGIN PRIVATE KEY-----
MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDBau6jp6KHwZhoaBDzW
v718SoqejQWW5UNAlWvee7o5IFviVA7aCE3NNnwdi5I3JNqhZANiAAQfVJJcXjvk
waVnfYhC8Y/CVADpu4IhkWd0EpUBZfu+NKb5SN4Xbqu2FX9Jv9beTNpWH99bAoFC
RLDSFCWjTRjA5uaGBmp/PJAEsbBjm7/Kemki8BO44h68UH+yqhkITak=
-----END PRIVATE KEY-----`

const ecP384Cert = `-----BEGIN CERTIFICATE-----
MIIDPjCCAsSgAwIBAgIUSmtppSueQuu0hij6ZW6wqL80QZkwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAX
DTI2MTAwNzE3MDMyOFoYDzk2OTIxMTI2MTcwMzI4WjBhMQswCQYDVQQGEwJVUzEN
MAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMRAw
DgYDVQQLDAdTaWduaW5nMREwDwYDVQQDDAhKb2huIERvZTB2MBAGByqGSM49AgEG
BSuBBAAiA2IABB9UklxeO+TBpWd9iELxj8JUAOm7giGRZ3QSlQFl+740pvlI3hdu
q7YVf0m/1t5M2lYf31sCgUJEsNIUJaNNGMDm5oYGan88kASxsGObv8p6aSLwE7ji
HrxQf7KqGQhNqaOCAT4wggE6MAkGA1UdEwQCMAAwCwYDVR0PBAQDAgbAMB0GA1Ud
JQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAzAtBgNVHR8EJjAkMCKgIKAehhxodHRw
Oi8vbG9jYWxob3N0OjgwODAvY2EuY3JsMIGRBggrBgEFBQcBAQSBhDCBgTAoBggr
BgEFBQcwAoYcaHR0cDovL2xvY2FsaG9zdDo4MDgwL2NhLmNydDAmBggrBgEFBQcw
AYYaaHR0cDovL2xvY2FsaG9zdDo4MDgwL29jc3AwLQYIKwYBBQUHMAGGIWh0dHA6
Ly9sb2NhbGhvc3Q6ODA4MC9vY3NwLWJhY2t1cDAdBgNVHQ4EFgQUAMnXv/lfG9/H
cpJCzD4/3bofy8QwHwYDVR0jBBgwFoAUOSTWoPatRsQJXByuxrwIMHU9h44wCgYI
KoZIzj0EAwIDaAAwZQIxAIFfMvslW5hsGcZAD8jHjHvMeBNV/hDXq5ngyVXcLeGc
Qa5RodWPaayGSyUvMmRmDQIwKwQrh6KCYPvya7Or+2cG9jEpLyqL2O60WT+3I6SB
t/41PNoaZmec7JJ0d01JbGFF
-----END CERTIFICATE-----`

const ecP384CaCert = `-----BEGIN CERTIFICATE-----
MIICTDCCAdKgAwIBAgIUY1k92EMEa5InU5MLz4E5CxLc7PMwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAX
DTI2MTAwNzE3MDMyOFoYDzk5NjYwOTEyMTcwMzI4WjBcMQswCQYDVQQGEwJVUzEN
MAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQsw
CQYDVQQLDAJDQTERMA8GA1UEAwwITXlSb290Q0EwdjAQBgcqhkjOPQIBBgUrgQQA
IgNiAATmRmRkbVv6AifK2l1yFCCJbK59tvvfhnz4ZEXOAeRvri/eGRj0OuOCdeXy
Utslo+FTRD8ZPx70iQQ7UWo78Xg5R9t/Go81kP6hukBjsECtu3lH6YuBvXzO6bit
uDi87I+jUzBRMB0GA1UdDgQWBBQ5JNag9q1GxAlcHK7GvAgwdT2HjjAfBgNVHSME
GDAWgBQ5JNag9q1GxAlcHK7GvAgwdT2HjjAPBgNVHRMBAf8EBTADAQH/MAoGCCqG
SM49BAMCA2gAMGUCMQDxMRw+GqC1WHTli/PflWghCerevLqrU+eKycoIxU2oTkI3
cTfJB2uvSqAd9NVkZQsCMEC27LP2idR3PZlVpX6P1HpNgxxhtxNdWnU/Dn7Dv4oo
fxH7sRa1atG25tnOKJ3SWQ==
-----END CERTIFICATE-----`

const ecP384CaCrl = `-----BEGIN X509 CRL-----
MIIBEzCBmwIBATAKBggqhkjOPQQDAjBcMQswCQYDVQQGEwJVUzENMAsGA1UECAwE
VGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYDVQQLDAJD
QTERMA8GA1UEAwwITXlSb290Q0EXDTI2MTAwNzE3MDMyOFoXDTQ4MDkwMTE3MDMy
OFqgDjAMMAoGA1UdFAQDAgEBMAoGCCqGSM49BAMCA2cAMGQCMEZ/ylzvI5fYtc1g
3nAZQfFtT4xk1pcuDU6UMs/YUcIR+TaISvHeEXrhKL+VpJIMfQIwED00Wj4MUNl9
yuVgLfEBFdBcd2Cj5uq92s+dWtnJX9kEoBazEYbujwlkylPl+GGz
-----END X509 CRL-----`

const ecP384OcspResponse = `-----BEGIN OCSP RESPONSE-----
MIIEGAoBAKCCBBEwggQNBgkrBgEFBQcwAQEEggP+MIID+jCCAQShZjBkMQswCQYD
VQQGEwJVUzENMAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoM
BU15T3JnMQ0wCwYDVQQLDARPQ1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlchgP
MjAyNjEwMDcxNzAzMjhaMGQwYjBNMAkGBSsOAwIaBQAEFMMBXUhH1UJjC9/mkAgx
tU0Ghr32BBQ5JNag9q1GxAlcHK7GvAgwdT2HjgIUSmtppSueQuu0hij6ZW6wqL80
QZmCABgPMjAyNjEwMDcxNzAzMjhaoSMwITAfBgkrBgEFBQcwAQIEEgQQa5o0YKKy
SthJZJzLJPabWDAKBggqhkjOPQQDAgNoADBlAjAgcq7RwCXoXdcom42c5p6UHcOO
9087SRNYNpJjsAoNru97ojmtrMam94Nytz2Nn5QCMQDBoA0NN942/rb2wXW5xTlk
ZSjvBjz1+zk6r002TgCO23r5EYYY6mFFE5yhIHqQfoygggJ4MIICdDCCAnAwggH2
oAMCAQICFEpraaUrnkLrtIYo+mVusKi/NEGaMAoGCCqGSM49BAMCMFwxCzAJBgNV
BAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UECgwF
TXlPcmcxCzAJBgNVBAsMAkNBMREwDwYDVQQDDAhNeVJvb3RDQTAgFw0yNjEwMDcx
NzAzMjhaGA85NjkyMTEyNjE3MDMyOFowZDELMAkGA1UEBhMCVVMxDTALBgNVBAgM
BFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzENMAsGA1UECwwE
T0NTUDEXMBUGA1UEAwwOT0NTUCBSZXNwb25kZXIwdjAQBgcqhkjOPQIBBgUrgQQA
IgNiAAR1G9v14K56RJNtMLCDrKIMVdQwRFg9PV7LzrkuY/Innvff6Qj8lrAQccit
zKj5oSvrJJxUiIAK/AkBcSJiCumjNqH40VNg92Gu0Ne3qfnub20EEjv3vdKZwgH4
WIOE0z+jbzBtMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgeAMBMGA1UdJQQMMAoGCCsG
AQUFBwMJMB0GA1UdDgQWBBS9zCyW7NVFJj2uxzTVLnDyRB66cjAfBgNVHSMEGDAW
gBQ5JNag9q1GxAlcHK7GvAgwdT2HjjAKBggqhkjOPQQDAgNoADBlAjEAoYSi3Dzd
ZBYmftTXiLsMmu3pQ4WIxNWEd4VmEf2FzOv97K1fihwmTeOH3ic712GEAjA2ODRE
Acs4puNv1yYCnSx23Ae8HHmdAOfs9QVjhFXZag4szdezHGAqHFOKx0wnlMY=
-----END OCSP RESPONSE-----`

function pemToUint8Array(
    pem: string | Uint8Array<ArrayBuffer>,
): Uint8Array<ArrayBuffer> {
    pem = typeof pem === 'string' ? pem : new TextDecoder().decode(pem)

    // Remove all headers, footers, and whitespace
    const b64 = pem
        .trim()
        .replace(/-----BEGIN [^-]+-----/, '')
        .replace(/-----END [^-]+-----/, '')
        .replace(/\s+/g, '')

    const binary = atob(b64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i)
    }

    return bytes
}

export const ecP384SigningKeys = {
    privateKey: pemToUint8Array(ecP384PrivateKeyPem),
    cert: pemToUint8Array(ecP384Cert),
    caCert: pemToUint8Array(ecP384CaCert),
    caCrl: pemToUint8Array(ecP384CaCrl),
    ocspResponse: pemToUint8Array(ecP384OcspResponse),
    privateKeyPem: ecP384PrivateKeyPem,
    certPem: ecP384Cert,
    caCertPem: ecP384CaCert,
    caCrlPem: ecP384CaCrl,
    ocspResponsePem: ecP384OcspResponse,
}
