const ecP521PrivateKeyPem = `-----BEGIN PRIVATE KEY-----
MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIAYwkAxb05UsXJPO9d
W0eGZsxQZgVavC7FmdJtap/8WNplS1twaU++4pZk3c+G1EMguxC8I/s7GTZ5/STb
BPZUFJahgYkDgYYABADDHV0JzEh/J4hW6sw8p3Pq8oD3kC66xqlyrlVR2V9+//0p
FGGtOU6fLOd0lrSAXpwl92O3XiaGtd+di0RvelupbgDbOBkO0oTEZYnZEg4VGF56
42ZjZtlwYkkulTKzFSSlla4v4DLVUr/1gZTzWKTb5ELhYa7AHXKWFtQAEgD3nZmZ
CA==
-----END PRIVATE KEY-----`

const ecP521Cert = `-----BEGIN CERTIFICATE-----
MIIDhjCCAuigAwIBAgIULLZF9bSy7jCCnYyEK+xc6V+0o4QwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMB4X
DTI1MTAwMTE5MDUzM1oXDTI2MTAwMTE5MDUzM1owYTELMAkGA1UEBhMCVVMxDTAL
BgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzEQMA4G
A1UECwwHU2lnbmluZzERMA8GA1UEAwwISm9obiBEb2UwgZswEAYHKoZIzj0CAQYF
K4EEACMDgYYABADDHV0JzEh/J4hW6sw8p3Pq8oD3kC66xqlyrlVR2V9+//0pFGGt
OU6fLOd0lrSAXpwl92O3XiaGtd+di0RvelupbgDbOBkO0oTEZYnZEg4VGF5642Zj
ZtlwYkkulTKzFSSlla4v4DLVUr/1gZTzWKTb5ELhYa7AHXKWFtQAEgD3nZmZCKOC
AT4wggE6MAkGA1UdEwQCMAAwCwYDVR0PBAQDAgbAMB0GA1UdJQQWMBQGCCsGAQUF
BwMEBggrBgEFBQcDAzAtBgNVHR8EJjAkMCKgIKAehhxodHRwOi8vbG9jYWxob3N0
OjgwODAvY2EuY3JsMIGRBggrBgEFBQcBAQSBhDCBgTAoBggrBgEFBQcwAoYcaHR0
cDovL2xvY2FsaG9zdDo4MDgwL2NhLmNydDAmBggrBgEFBQcwAYYaaHR0cDovL2xv
Y2FsaG9zdDo4MDgwL29jc3AwLQYIKwYBBQUHMAGGIWh0dHA6Ly9sb2NhbGhvc3Q6
ODA4MC9vY3NwLWJhY2t1cDAdBgNVHQ4EFgQU2iOXXdn54ON/jiVB8WI9cRydlSUw
HwYDVR0jBBgwFoAUQUjlCHHsPp953KrJfg19Ok30FhQwCgYIKoZIzj0EAwIDgYsA
MIGHAkF9PKWlzgGsJmpoTkE3TobVCe/y0cWEyoMboIvidekozA+MQGUjDycX82Pe
PlglwsrLM2G/lZ2yqLl/uAvht7/XoQJCAPNfNpGMkM01V9lztBvkbLHCznMZz7fK
BPH4BGFvC0urp+pXE2JFWJC8ZDVyJBvkngKAez7khrbnykYIxSr02KeM
-----END CERTIFICATE-----`

const ecP521CaCert = `-----BEGIN CERTIFICATE-----
MIIClTCCAfagAwIBAgIUCu9bQwKoUOhf/JxsHUsx1JqRiUswCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMB4X
DTI1MTAwMTE5MDUzM1oXDTM1MDkyOTE5MDUzM1owXDELMAkGA1UEBhMCVVMxDTAL
BgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzELMAkG
A1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMIGbMBAGByqGSM49AgEGBSuBBAAj
A4GGAAQAEa05kS3I4hP0FJU7FKUHzr+mRSvJ31JOm7FMHo+K8p8aqn8uj4crIi1q
P0e2iyrsfg+9GTHkQdRDtnByubUJKJEBOlDmKgtgI9LZfO5GRTevjXA3bRoj4Ie6
DGYtpk2LV+tc1Yz9a8rkVbaNzetbZT/69N4NkrBnKA0unY/uEHi1iFCjUzBRMB0G
A1UdDgQWBBRBSOUIcew+n3ncqsl+DX06TfQWFDAfBgNVHSMEGDAWgBRBSOUIcew+
n3ncqsl+DX06TfQWFDAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA4GMADCB
iAJCASwLc+0N0JI3s1g4mQ4sxvotoOyznQt/ZluRBzOyI1bWE+IndkXXzn3pZN3F
muokV7/Hdq6CnnS4GnlywHAyOKqdAkIBtGQ6XJ6jOK38OeuFcScqJbk523YeptFN
npJ6mHBojNVN3IOQXwOhRapMfyMQQxox1W8rn1Wr83MxhwQYeESNBLI=
-----END CERTIFICATE-----`

const ecP521CaCrl = `-----BEGIN X509 CRL-----
MIIBOTCBmwIBATAKBggqhkjOPQQDAjBcMQswCQYDVQQGEwJVUzENMAsGA1UECAwE
VGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYDVQQLDAJD
QTERMA8GA1UEAwwITXlSb290Q0EXDTI1MTAwMTE5MDUzM1oXDTI1MTAzMTE5MDUz
M1qgDjAMMAoGA1UdFAQDAgEBMAoGCCqGSM49BAMCA4GMADCBiAJCAVSbgxoQstIO
Oo9nWeU3Df4sLKAeg4hu2sQs8eV9YEUvgr2IP2AAqDcd2U6DX7g/mazhfJPeGdyX
UIYHc2UK8kMQAkIBzuYNsFiw8FMiWvyIo+IwsQgpDX7ePfY1vgxG4zUNAXNjg3Yt
A58SMMHLZix1wDy8L1rXea0/Xz21H+Lo5BqdqEc=
-----END X509 CRL-----`

const ecP521OcspResponse = `-----BEGIN OCSP RESPONSE-----
MIIEhwoBAKCCBIAwggR8BgkrBgEFBQcwAQEEggRtMIIEaTCCAQShZjBkMQswCQYD
VQQGEwJVUzENMAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoM
BU15T3JnMQ0wCwYDVQQLDARPQ1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlchgP
MjAyNTEwMDExOTA1MzNaMGQwYjBNMAkGBSsOAwIaBQAEFMMBXUhH1UJjC9/mkAgx
tU0Ghr32BBRBSOUIcew+n3ncqsl+DX06TfQWFAIULLZF9bSy7jCCnYyEK+xc6V+0
o4SCABgPMjAyNTEwMDExOTA1MzNaoSMwITAfBgkrBgEFBQcwAQIEEgQQiZUI0NXf
MVPn2hyVofgCPjAKBggqhkjOPQQDAgOBjAAwgYgCQgGKphghfZ6Lx+VCzD8GS1Ym
vMNjWfUXahqlYHFYVPCkSbo7sIBL1pEn2qXLF7L8oIAyJRqEXdnGU3cPUOx/xDux
4QJCAd50Jdd8Bm3n+BXIP3VJpYuVTPkeR5wH8H+O5oXbX6Q/iLGvGsHDhVvIlm8n
ZcxIzzvnRf2zz4oP78Wk3MHzKfzRoIICwjCCAr4wggK6MIICHKADAgECAhQstkX1
tLLuMIKdjIQr7FzpX7SjhTAKBggqhkjOPQQDAjBcMQswCQYDVQQGEwJVUzENMAsG
A1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYD
VQQLDAJDQTERMA8GA1UEAwwITXlSb290Q0EwIBcNMjUxMDAxMTkwNTMzWhgPMjA1
MzAyMTYxOTA1MzNaMGQxCzAJBgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYD
VQQHDAVMb2NhbDEOMAwGA1UECgwFTXlPcmcxDTALBgNVBAsMBE9DU1AxFzAVBgNV
BAMMDk9DU1AgUmVzcG9uZGVyMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBSC6a
YXt3rZfs2l++DKrHdkVpjs0jIFHXbBABtL2uUA/qgU3dihlOPJfr5wTsvRYiUTj6
Qt8tlz+0z752Fv8dqvMBED3hn6WBkgN4e3iu1glAmcZUdat9ENCSyhmfUobdfBGe
b/Dj/Q2J1LFvi+KttqRN48Kk9rSc7/d6W5aB9AuUi6+jbzBtMAkGA1UdEwQCMAAw
CwYDVR0PBAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMJMB0GA1UdDgQWBBTwxjZL
N07C75ExnmK0ffIAUVWtBTAfBgNVHSMEGDAWgBRBSOUIcew+n3ncqsl+DX06TfQW
FDAKBggqhkjOPQQDAgOBiwAwgYcCQgFfJhty0ibgXEJZQM0jnrvvwLDwOhPMLN3x
7mpJLtlt+meJqjKCiFmBH9hX/mGVpTGqCdTo87odrFmHt+ahhkYSNAJBWSYtQ23H
kg7HT5Cyu8tqftASwgvxJb1eJIvnpRsYmiKjdDfNOb/CSaeVL4dIGn/UHS3vuUoy
ZdV5DiiodAtOzEg=
-----END OCSP RESPONSE-----`

function pemToUint8Array(
    pem: string | Uint8Array<ArrayBuffer>,
): Uint8Array<ArrayBuffer> {
    pem = typeof pem === 'string' ? pem : new TextDecoder().decode(pem)

    // Remove all headers, footers, and whitespace
    const b64 = pem
        .trim()
        .replace(/-----BEGIN [^-]+-----/, '')
        .replace(/-----END [^-]+-----/, '')
        .replace(/\s+/g, '')

    const binary = atob(b64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i)
    }

    return bytes
}

export const ecP521SigningKeys = {
    privateKey: pemToUint8Array(ecP521PrivateKeyPem),
    cert: pemToUint8Array(ecP521Cert),
    caCert: pemToUint8Array(ecP521CaCert),
    caCrl: pemToUint8Array(ecP521CaCrl),
    ocspResponse: pemToUint8Array(ecP521OcspResponse),
    privateKeyPem: ecP521PrivateKeyPem,
    certPem: ecP521Cert,
    caCertPem: ecP521CaCert,
    caCrlPem: ecP521CaCrl,
    ocspResponsePem: ecP521OcspResponse,
}
