const ecP521PrivateKeyPem = `-----BEGIN PRIVATE KEY-----
MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIAiggp+paSoV56DuJO
b4QA53AgdwXb/YUT0kGG/uxVw9MmNZYF/ZLQQsQ38UbDy5oKc65Cep2K2ccLtOn6
DP8LDOqhgYkDgYYABACEigbXZ9bjxco0V5j3s5dEBV/0d19AF1XfFxoPEWmlkajA
s9PcYMivtA4uqR6UCdmRLYARSl5Vzq8he7ffPLcsbwDJSzpJeEHXgej1e8xxyhXa
hVN0ds3DwfBSTWyobmwq94bTD7qQEm50cY00YFGp9mAjGRW7WoWuwbhtL64MI/bR
3Q==
-----END PRIVATE KEY-----`

const ecP521Cert = `-----BEGIN CERTIFICATE-----
MIIDhjCCAuigAwIBAgIUWDUGC7vnwptIw6ZS3NUZOzdfUvgwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMB4X
DTI1MDkyMTEwNTkxOFoXDTI2MDkyMTEwNTkxOFowYTELMAkGA1UEBhMCVVMxDTAL
BgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzEQMA4G
A1UECwwHU2lnbmluZzERMA8GA1UEAwwISm9obiBEb2UwgZswEAYHKoZIzj0CAQYF
K4EEACMDgYYABACEigbXZ9bjxco0V5j3s5dEBV/0d19AF1XfFxoPEWmlkajAs9Pc
YMivtA4uqR6UCdmRLYARSl5Vzq8he7ffPLcsbwDJSzpJeEHXgej1e8xxyhXahVN0
ds3DwfBSTWyobmwq94bTD7qQEm50cY00YFGp9mAjGRW7WoWuwbhtL64MI/bR3aOC
AT4wggE6MAkGA1UdEwQCMAAwCwYDVR0PBAQDAgbAMB0GA1UdJQQWMBQGCCsGAQUF
BwMEBggrBgEFBQcDAzAtBgNVHR8EJjAkMCKgIKAehhxodHRwOi8vbG9jYWxob3N0
OjgwODAvY2EuY3JsMIGRBggrBgEFBQcBAQSBhDCBgTAoBggrBgEFBQcwAoYcaHR0
cDovL2xvY2FsaG9zdDo4MDgwL2NhLmNydDAmBggrBgEFBQcwAYYaaHR0cDovL2xv
Y2FsaG9zdDo4MDgwL29jc3AwLQYIKwYBBQUHMAGGIWh0dHA6Ly9sb2NhbGhvc3Q6
ODA4MC9vY3NwLWJhY2t1cDAdBgNVHQ4EFgQUbUxtCuggCQekeoOInfV7JAcFU9Uw
HwYDVR0jBBgwFoAU73WNI8XD8eqcm4WCoCAE3Er/E18wCgYIKoZIzj0EAwIDgYsA
MIGHAkFxSF9WHTqZknYb3Ix3PCYtlL998OlNY4ldNLj1FgBaS/o6H7rRKkYriJzI
kaSI77tGbiEM5FqM66lu2Tifw5bGZAJCAcrY5T9WOFBIHCnWIUIE+fBNnnmod11g
54mZ/jtA6CX/pcGnvnNPypaefZ2ZV0KbCPrmExlHERM0Z2CpcK33uDJv
-----END CERTIFICATE-----`

const ecP521CaCert = `-----BEGIN CERTIFICATE-----
MIIClTCCAfagAwIBAgIUZK4316sL6Q55/V7oJkD+AtNzWpUwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMB4X
DTI1MDkyMTEwNTkxOFoXDTM1MDkxOTEwNTkxOFowXDELMAkGA1UEBhMCVVMxDTAL
BgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzELMAkG
A1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMIGbMBAGByqGSM49AgEGBSuBBAAj
A4GGAAQAVC0Xz410KG9tlca/bLL9M3RC1sQiYa93kwjiiy1G5YuoD+VKHnzYPAN0
s4JNz0mbhy8kNo+OXMZL6yYksHztWVkBXfgJt3c9S+rnPJ2uo8cq08bk4APkTpNe
3/wzY1pxLs2vuuyMCpLyBY5Br/Dn7Aja/Yw7RLN9BJVfEBqECKiHp62jUzBRMB0G
A1UdDgQWBBTvdY0jxcPx6pybhYKgIATcSv8TXzAfBgNVHSMEGDAWgBTvdY0jxcPx
6pybhYKgIATcSv8TXzAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA4GMADCB
iAJCAQuk//yIwatcLhFy3YzZ5w3uq8a4Ea/oo2HTtIzwUxWFlOI/ATsq50QhcZ8K
tcXjgx1qzgfJw71/Bh5WKOQYrfnCAkIBfLHJlOydoylMuGvoVCKfZee1TIUYqLDi
x9AgFXfhiaCFmTAVqy8r4WDJXsRgj1DsEN87VA73/2sZ7spgfbc8/O8=
-----END CERTIFICATE-----`

const ecP521CaCrl = `-----BEGIN X509 CRL-----
MIIBODCBmwIBATAKBggqhkjOPQQDAjBcMQswCQYDVQQGEwJVUzENMAsGA1UECAwE
VGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYDVQQLDAJD
QTERMA8GA1UEAwwITXlSb290Q0EXDTI1MDkyMTEwNTkxOFoXDTI1MTAyMTEwNTkx
OFqgDjAMMAoGA1UdFAQDAgEBMAoGCCqGSM49BAMCA4GLADCBhwJCARIH3xuJ5rAk
XD6K+e2bbKKEyQlBPLotlIW/qRoLSlIjB1bGE1ter8CEpng2/axBtQI+1qKf64sj
DSGRELPytGFAAkFUVTIIioAE+nUZb4jJE00go4pbtJUuwljKbhjUPCjesxPw6jyw
D3xqt9ELoG0RjhEo4gJD6HaO0UI8v3jt7WDdGQ==
-----END X509 CRL-----`

const ecP521OcspResponse = `-----BEGIN OCSP RESPONSE-----
MIIEhwoBAKCCBIAwggR8BgkrBgEFBQcwAQEEggRtMIIEaTCCAQShZjBkMQswCQYD
VQQGEwJVUzENMAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoM
BU15T3JnMQ0wCwYDVQQLDARPQ1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlchgP
MjAyNTA5MjExMDU5MThaMGQwYjBNMAkGBSsOAwIaBQAEFMMBXUhH1UJjC9/mkAgx
tU0Ghr32BBTvdY0jxcPx6pybhYKgIATcSv8TXwIUWDUGC7vnwptIw6ZS3NUZOzdf
UviCABgPMjAyNTA5MjExMDU5MThaoSMwITAfBgkrBgEFBQcwAQIEEgQQoD81oWPK
Gbz0NxmaYmbXyzAKBggqhkjOPQQDAgOBiwAwgYcCQgCOBTta+D4sFxwwrMeQZw4Q
1jgo7F1noEDhgS8Eyl0nuXhJFHZvoW98U+DC6qVpiZuwHCYYI2QzMqFmVpINYOHo
WwJBcYFsiAi9mn1U/1lcOpr0du2kp4nhoWtDZzqjLOnTEDa0VwRXz/dCuKhltPRs
oS5ceWsDfsGxBsN8I3SKPvYYE+CgggLDMIICvzCCArswggIcoAMCAQICFFg1Bgu7
58KbSMOmUtzVGTs3X1L5MAoGCCqGSM49BAMCMFwxCzAJBgNVBAYTAlVTMQ0wCwYD
VQQIDARUZXN0MQ4wDAYDVQQHDAVMb2NhbDEOMAwGA1UECgwFTXlPcmcxCzAJBgNV
BAsMAkNBMREwDwYDVQQDDAhNeVJvb3RDQTAgFw0yNTA5MjExMDU5MThaGA8yMDUz
MDIwNjEwNTkxOFowZDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNV
BAcMBUxvY2FsMQ4wDAYDVQQKDAVNeU9yZzENMAsGA1UECwwET0NTUDEXMBUGA1UE
AwwOT0NTUCBSZXNwb25kZXIwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABADXmvPP
IafZV7lUHi5azB1r0Aje9A8Cr2MI6SXn2kjth5AToywKglKrD8hZV9cCCdWozLR1
Ef5jBQyIphaObcBwGgCHGUh/+GWlLm2EaQjOlHFP1dKciOxbi+76jUtGFYGyYlqC
dNaHhMcG+qozv4hZ2f8eKMZ4GxCiDZ7VyrCkm3m1RqNvMG0wCQYDVR0TBAIwADAL
BgNVHQ8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwkwHQYDVR0OBBYEFOSsKzDr
QUY4Kv+EIyNalprBIsVeMB8GA1UdIwQYMBaAFO91jSPFw/HqnJuFgqAgBNxK/xNf
MAoGCCqGSM49BAMCA4GMADCBiAJCAQMGD2sZm8dzZQhB09Wn1zds670w0TUswju5
fyJVexAYYQfhlh65Th5TlFrVnsYBh6sCw/CD8Of2iwb9gzrc0oxqAkIBTqw5i3Hq
WsURmmrFArPvgnDtcnSLx9H2IVaF1p40KyqUYafMllEC33dD+CZ4SE8j+ixcHypK
ENYnR0N7oKNLNPw=
-----END OCSP RESPONSE-----`

function pemToUint8Array(pem: string | Uint8Array): Uint8Array {
    pem = typeof pem === 'string' ? pem : new TextDecoder().decode(pem)

    // Remove all headers, footers, and whitespace
    const b64 = pem
        .trim()
        .replace(/-----BEGIN [^-]+-----/, '')
        .replace(/-----END [^-]+-----/, '')
        .replace(/\s+/g, '')

    const binary = atob(b64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i)
    }

    return bytes
}

export const ecP521SigningKeys = {
    privateKey: pemToUint8Array(ecP521PrivateKeyPem),
    cert: pemToUint8Array(ecP521Cert),
    caCert: pemToUint8Array(ecP521CaCert),
    caCrl: pemToUint8Array(ecP521CaCrl),
    ocspResponse: pemToUint8Array(ecP521OcspResponse),
    privateKeyPem: ecP521PrivateKeyPem,
    certPem: ecP521Cert,
    caCertPem: ecP521CaCert,
    caCrlPem: ecP521CaCrl,
    ocspResponsePem: ecP521OcspResponse,
}
