const ecP521PrivateKeyPem = `-----BEGIN PRIVATE KEY-----
MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIB0W7ZD0hPue/CkGv+
K0hxUTHpSfTmdvw+hUOAsndKovjzKbRDFQU1XMHDmNYKgfd2/XKXKKfAhVoVYfgr
hNYqjLChgYkDgYYABAHN4+xlMRfM/5p/mawzC2Xlm4+vu+JIYKj0ShhXjLaLMkwg
h8oFnyS4bf1IGjPiYHU7CrwcGgsoE5DQGraYG9n9YQBZNOKKqmqbkZlgsv1RzpYB
Md6ppRx91gBrtNOqf8lB7Dm60e06p6KfG9/YyuS30HGcrdHUUs7zhRy3wTn8Lu1/
qw==
-----END PRIVATE KEY-----`

const ecP521Cert = `-----BEGIN CERTIFICATE-----
MIIDiDCCAuqgAwIBAgIUWfHLxCwoCnCfUzSjVlBLDjdI8+MwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAX
DTI2MTAwNzE3MDMyOVoYDzk2OTIxMTI2MTcwMzI5WjBhMQswCQYDVQQGEwJVUzEN
MAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMRAw
DgYDVQQLDAdTaWduaW5nMREwDwYDVQQDDAhKb2huIERvZTCBmzAQBgcqhkjOPQIB
BgUrgQQAIwOBhgAEAc3j7GUxF8z/mn+ZrDMLZeWbj6+74khgqPRKGFeMtosyTCCH
ygWfJLht/UgaM+JgdTsKvBwaCygTkNAatpgb2f1hAFk04oqqapuRmWCy/VHOlgEx
3qmlHH3WAGu006p/yUHsObrR7Tqnop8b39jK5LfQcZyt0dRSzvOFHLfBOfwu7X+r
o4IBPjCCATowCQYDVR0TBAIwADALBgNVHQ8EBAMCBsAwHQYDVR0lBBYwFAYIKwYB
BQUHAwQGCCsGAQUFBwMDMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6Ly9sb2NhbGhv
c3Q6ODA4MC9jYS5jcmwwgZEGCCsGAQUFBwEBBIGEMIGBMCgGCCsGAQUFBzAChhxo
dHRwOi8vbG9jYWxob3N0OjgwODAvY2EuY3J0MCYGCCsGAQUFBzABhhpodHRwOi8v
bG9jYWxob3N0OjgwODAvb2NzcDAtBggrBgEFBQcwAYYhaHR0cDovL2xvY2FsaG9z
dDo4MDgwL29jc3AtYmFja3VwMB0GA1UdDgQWBBQ3R3ubQI14091OKxDjw4YsOLLp
2TAfBgNVHSMEGDAWgBSj0yuC/ZxYKBQSIBj2DDvj1XZvcTAKBggqhkjOPQQDAgOB
iwAwgYcCQgEVTy9y9m5ATh4oNX35SQ0JjzwyOu3kqb0xKLDxcfWcwnEVONqvGfl+
xyMW9rRcPDWQVhCOLhQlkxFCWVtkEQoZ+gJBMAQdDrZZw5tav/wIzJS5cUh9vG6E
YAxHRxy2jpPayELtjcC848k4KQEuOevUHnij9lCrgZL8FflpV79rz943cvE=
-----END CERTIFICATE-----`

const ecP521CaCert = `-----BEGIN CERTIFICATE-----
MIIClzCCAfigAwIBAgIUW+2dLBnIBGq2x0OUaqIydmE333owCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDjAMBgNVBAcMBUxvY2FsMQ4w
DAYDVQQKDAVNeU9yZzELMAkGA1UECwwCQ0ExETAPBgNVBAMMCE15Um9vdENBMCAX
DTI2MTAwNzE3MDMyOVoYDzk5NjYwOTEyMTcwMzI5WjBcMQswCQYDVQQGEwJVUzEN
MAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQsw
CQYDVQQLDAJDQTERMA8GA1UEAwwITXlSb290Q0EwgZswEAYHKoZIzj0CAQYFK4EE
ACMDgYYABACmntUifMjqU3Hu/zwJzY/SLn8/EhuUqYA+WmWVzJ2N0FPbTXQ05rez
ff1KbIXiKg4f6YBxQcMFCSGEJOBa2asPhQBM8Re2HPbh/WLBAWTiPsnNAzp8T0A7
B1DhFlpld3boIqUZO5N5y7oF6zYCbp3+lvsoK6cURK+1JGr2Hrzi4wFDJaNTMFEw
HQYDVR0OBBYEFKPTK4L9nFgoFBIgGPYMO+PVdm9xMB8GA1UdIwQYMBaAFKPTK4L9
nFgoFBIgGPYMO+PVdm9xMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDgYwA
MIGIAkIA+ogOXL9kFJMZh0E4RyDM3qwT+ECOmq70/gKy2dVgJ8UkAQd4T94vt9ml
VVDp7qEgvzqScgrg7Y1gYbN+nkaU//kCQgCN9STzzK45WbX7b83Dv67tImkfivi+
uAdkIXBgTHesFP4GnnTNLEYp3TQ/Y9gVSrEARPsJkORKRodlFf8LZ/EF5g==
-----END CERTIFICATE-----`

const ecP521CaCrl = `-----BEGIN X509 CRL-----
MIIBODCBmwIBATAKBggqhkjOPQQDAjBcMQswCQYDVQQGEwJVUzENMAsGA1UECAwE
VGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYDVQQLDAJD
QTERMA8GA1UEAwwITXlSb290Q0EXDTI2MTAwNzE3MDMyOVoXDTQ4MDkwMTE3MDMy
OVqgDjAMMAoGA1UdFAQDAgEBMAoGCCqGSM49BAMCA4GLADCBhwJBYm1bOIUDPiuk
ILWngJ0ZfONwvlL0v49wf/hiEtk/cLCPVwZUSqg8FPpGydhM5SE9a9TK7Hx5CtQF
w6qftW3dpoECQgGUPpKtfpBDlpK1DxICUOC0qzahcFtKDDnJCPmwaH4CkztzDDIy
arA6UD5UBOOvaficN400T8gY80YDEOQ8KuD3Cg==
-----END X509 CRL-----`

const ecP521OcspResponse = `-----BEGIN OCSP RESPONSE-----
MIIEhwoBAKCCBIAwggR8BgkrBgEFBQcwAQEEggRtMIIEaTCCAQShZjBkMQswCQYD
VQQGEwJVUzENMAsGA1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoM
BU15T3JnMQ0wCwYDVQQLDARPQ1NQMRcwFQYDVQQDDA5PQ1NQIFJlc3BvbmRlchgP
MjAyNjEwMDcxNzAzMjlaMGQwYjBNMAkGBSsOAwIaBQAEFMMBXUhH1UJjC9/mkAgx
tU0Ghr32BBSj0yuC/ZxYKBQSIBj2DDvj1XZvcQIUWfHLxCwoCnCfUzSjVlBLDjdI
8+OCABgPMjAyNjEwMDcxNzAzMjlaoSMwITAfBgkrBgEFBQcwAQIEEgQQVhGlvKbM
NKyBWeQD2/dP/jAKBggqhkjOPQQDAgOBjAAwgYgCQgH05ftxrPfT9ygfQvbFtvz/
apJjVovM9tT2qkq5jeFkTvhzs9zf6LCMLw38Z9NUsvCxufoH12DsPk428DYqnitw
FAJCAU01zcxz10GRqDiLpxdMRw2BSvVXB1c0Fuu5cQQZnaRvFOI0Xc2YkoCz/zH0
cLQyav9Z8IP05Fg64tvc10DwQyGmoIICwjCCAr4wggK6MIICHKADAgECAhRZ8cvE
LCgKcJ9TNKNWUEsON0jz5DAKBggqhkjOPQQDAjBcMQswCQYDVQQGEwJVUzENMAsG
A1UECAwEVGVzdDEOMAwGA1UEBwwFTG9jYWwxDjAMBgNVBAoMBU15T3JnMQswCQYD
VQQLDAJDQTERMA8GA1UEAwwITXlSb290Q0EwIBcNMjYxMDA3MTcwMzI5WhgPOTY5
MjExMjYxNzAzMjlaMGQxCzAJBgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0MQ4wDAYD
VQQHDAVMb2NhbDEOMAwGA1UECgwFTXlPcmcxDTALBgNVBAsMBE9DU1AxFzAVBgNV
BAMMDk9DU1AgUmVzcG9uZGVyMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQB+eUR
thZbWU7FSV3VO8AxmBYKk7bXtzlQjZ3H+f2fwkAG1NQJLp25lI1yfTBpzTPlGdeu
dz/yDFaJb/efp7PLqi4BW6z6HSppYx02DdHpYB2cRgIMfeEJrUZgFrLv1BMHxBWf
55IRARK7b+po8BmURTVacHd5FhPdBymDW1f3kNz32u6jbzBtMAkGA1UdEwQCMAAw
CwYDVR0PBAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMJMB0GA1UdDgQWBBTjlvR2
1Xi0vYiKPrVYRv0cKa6h7jAfBgNVHSMEGDAWgBSj0yuC/ZxYKBQSIBj2DDvj1XZv
cTAKBggqhkjOPQQDAgOBiwAwgYcCQgCMiOQ0ooovU7NQNGvPrVNp80IjNsQTm06n
JL3F2wdx0dITWSdlcjddGIKr8fq8m7bsJUzPyl6kAn7qm6tt1UwatgJBXfZzXSY8
vuEFm+JGBEGBh4lvDqNtydWmZVc4QIw96EXMNySBn9u0lIhq5pvLvOQyyjMy+YHK
fDjODDX9zEXI59Q=
-----END OCSP RESPONSE-----`

function pemToUint8Array(
    pem: string | Uint8Array<ArrayBuffer>,
): Uint8Array<ArrayBuffer> {
    pem = typeof pem === 'string' ? pem : new TextDecoder().decode(pem)

    // Remove all headers, footers, and whitespace
    const b64 = pem
        .trim()
        .replace(/-----BEGIN [^-]+-----/, '')
        .replace(/-----END [^-]+-----/, '')
        .replace(/\s+/g, '')

    const binary = atob(b64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i)
    }

    return bytes
}

export const ecP521SigningKeys = {
    privateKey: pemToUint8Array(ecP521PrivateKeyPem),
    cert: pemToUint8Array(ecP521Cert),
    caCert: pemToUint8Array(ecP521CaCert),
    caCrl: pemToUint8Array(ecP521CaCrl),
    ocspResponse: pemToUint8Array(ecP521OcspResponse),
    privateKeyPem: ecP521PrivateKeyPem,
    certPem: ecP521Cert,
    caCertPem: ecP521CaCert,
    caCrlPem: ecP521CaCrl,
    ocspResponsePem: ecP521OcspResponse,
}
