name: Deploy Docs

on:
    push:
        branches:
            - master
            - docs/* # Useful for testing changes to docs
        tags:
            - 'v*.*.*' # Trigger on version tags like v1.0.0, v2.1.3, etc.
            - 'v*'
            - 'latest'

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

defaults:
    run:
        shell: bash

jobs:
    build:
        name: Build Docs for ${{ matrix.version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: 
                  - v1
                  - latest
                  - ${{ github.ref_name }}
        steps:
            - name: Checkout ${{ matrix.version }}
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
              with:
                  ref: ${{ matrix.version }}
            - name: Get formatted ref name
              id: formatted-ref-name
              run: echo "formatted_ref_name=${{ matrix.version }}" | sed 's/\//_/g' >> $GITHUB_OUTPUT
            - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
              with:
                  run_install: true
            - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
              with:
                  node-version: '24'
                  cache: 'pnpm'
            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b #v5
            - name: Compile TypeScript
              run: pnpm compile
            - name: Build docs
              run: pnpm docs:gen ${{ matrix.version }}
            - name: Copy latest to root
              if: matrix.version == 'latest'
              run: cp -r docs-html/latest/* docs-html/
            - name: Upload artifact
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
              with:
                  name: docs-${{ steps.formatted-ref-name.outputs.formatted_ref_name }}
                  path: ./docs-html
                  retention-days: 1
            - name: Where to find the docs
              run: echo "You can find the documentation for version ${{ matrix.version }} at https://jacobshirley.github.io/pki-lite/${{ steps.formatted-ref-name.outputs.formatted_ref_name }}" >> $GITHUB_STEP_SUMMARY
    combine:
        name: Combine Docs
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
              with:
                  merge-multiple: true
                  path: ./docs-html
            - name: Upload combined artifact
              uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
              with:
                  path: ./docs-html
                  retention-days: 1
                  name: 'github-pages'

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: combine
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e #v4
