name: Pre-Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to prerelease as (e.g. patch, minor, major)'
        required: true
      preid:
        description: 'Prerelease identifier (e.g. alpha, beta, rc)'
        required: false
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  prerelease:
    runs-on: ubuntu-latest
    name: Pre-Release
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          run_install: true
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --only-shell
      - name: Compile
        run: pnpm compile
      - name: Bump version
        run: ./scripts/bump-version.sh ${{ github.event.inputs.version }} --preid='${{ github.event.inputs.preid }}'
      - name: Pack
        run: pnpm pack -r
      - name: Push artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          path: ./*.tgz
          name: pki-lite
