name: Test
on:
    push:
        branches:
            - master
            - ci/test # For testing changes to this workflow
    pull_request:
        branches:
            - master
    merge_group:
    workflow_dispatch:
    workflow_call:
permissions:
    contents: read
    actions: read
    checks: write
jobs:
    Tests:
        runs-on: ubuntu-latest
        name: Tests
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
              with:
                  run_install: true
            - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
              with:
                  node-version: '24'
                  cache: 'pnpm'
            - name: Install Playwright Browsers
              run: pnpm exec playwright install chromium --only-shell
            - name: Compile
              run: pnpm compile
            - name: Run tests
              run: pnpm test
